version: 2.1

jobs:
  build:
    docker:
      - image: python:3.8
    working_directory: ~/repo
    steps:
      - checkout
      - run: pip install -r requirements.txt
      - run: python manage.py migrate
      - run: flake8
