# Generated by Django 4.1.7 on 2023-03-22 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drf', '0002_author_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Author',
        ),
    ]
